In [1]:
#!/usr/bin/env python
import snowflake.connector as c
import pandas as pd
import matplotlib.pyplot as plt
# Gets the version
ctx = c.connect(user='DEEPIKA',password='Life@123',account='go75189.us-east-2.aws')

C:\Users\Deepika\anaconda3\envs\cows\lib\site-packages\snowflake\connector\options.py:78: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<0.18.0,>=0.17.0; extra == "pandas"'
  warn_incompatible_dep('pyarrow', _installed_pyarrow_version.version, _expected_pyarrow_version)

In [2]:
sql = "SELECT * FROM BENCHPREP_DATASET.PUBLIC.TABLE3"

In [3]:
df = pd.read_sql(sql, ctx)

In [4]:
df.head()

,COURSE,USER_REGISTRATION_YEAR,ID_USER,USER_PROFILE,REGION,COURSE_LEVEL,AGE_BAND,NUM_OF_PREV_ATTEMPTS,STUDIED_CREDITS,QUALIFICATION,...,TENANTS,RECOMMEND_COURSE_PRIORITY,ARE_YOU_HAPPY_WITH_COURSE,PROJECTS_IN_THE_COURSE,PROJECTS_COMPLETED,MARKS,PENDING_PROJECTS,CATEGORY,ISCOURSERETIRED,COURSE_RATING
0,Python,2013,583968,Student,Leicester,Beginner,0-35,0.0,60.0,Graduate,...,Class Plus,High,1.0,277.0,80.0,89.0,197.0,Python Programming Essentials,0,3
1,Python,2013,563230,Student,Hampshire,Beginner,0-35,0.0,60.0,Graduate,...,WizIQ,Very Low,1.0,288.0,80.0,92.0,208.0,Using Python to Interact with the Operating Sy...,0,2
2,Python,2012,388754,Student,Oxfordshire,Beginner,0-35,0.0,120.0,Graduate,...,Byjus,High,1.0,268.0,92.0,84.0,176.0,"""Python Project: pillow",tesseract,"and opencv"""
3,Python,2013,2394090,Professional,Norfolk,Beginner,0-35,0.0,90.0,Graduate,...,Embibe,Very High,0.0,299.0,100.0,86.0,199.0,Create Your First Python Program,1,4
4,Python,2012,572898,Professional,Hampshire,Beginner,0-35,0.0,120.0,Graduate,...,Toppr,Medium,0.0,252.0,83.0,88.0,169.0,Python Geospatial Data Analysis,1,4

In [5]:
df.dropna(inplace = True)

In [6]:
df.tail()

,COURSE,USER_REGISTRATION_YEAR,ID_USER,USER_PROFILE,REGION,COURSE_LEVEL,AGE_BAND,NUM_OF_PREV_ATTEMPTS,STUDIED_CREDITS,QUALIFICATION,...,TENANTS,RECOMMEND_COURSE_PRIORITY,ARE_YOU_HAPPY_WITH_COURSE,PROJECTS_IN_THE_COURSE,PROJECTS_COMPLETED,MARKS,PENDING_PROJECTS,CATEGORY,ISCOURSERETIRED,COURSE_RATING
26229,Deep learning,2014,687586,Student,Cheshire,Intermediate,0-35,0.0,30.0,Graduate,...,EduKart,Very Low,1.0,253.0,20.0,77.0,233.0,An Introduction to Practical Deep Learning,1,4
26230,Deep learning,2014,694070,Professional,Oxfordshire,Intermediate,35-55,0.0,30.0,Graduate,...,Udemy,Medium,1.0,254.0,90.0,86.0,164.0,Introduction to Deep Learning,0,3
26231,Deep learning,2014,696710,Professional,Oxfordshire,Intermediate,0-35,0.0,30.0,Graduate,...,Coursera,High,1.0,261.0,10.0,60.0,251.0,An Introduction to Practical Deep Learning,1,1
26232,Deep learning,2014,690065,Professional,Oxfordshire,Intermediate,35-55,0.0,30.0,Post Graduate,...,Brainly,Low,0.0,272.0,10.0,40.0,262.0,Introduction to Deep Learning & Neural Network...,1,5
26233,Deep learning,2014,698065,Professional,Norfolk,Intermediate,0-35,0.0,60.0,Graduate,...,Unacademy,Very High,0.0,250.0,0.0,0.0,250.0,Build a Deep Learning Based Image Classifier w...,1,5

In [7]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
df.columns

Index(['COURSE', 'USER_REGISTRATION_YEAR', 'ID_USER', 'USER_PROFILE', 'REGION',
       'COURSE_LEVEL', 'AGE_BAND', 'NUM_OF_PREV_ATTEMPTS', 'STUDIED_CREDITS',
       'QUALIFICATION', 'FINAL_RESULT', 'COURSE_REGISTRATION_IN_DAYS',
       'COURSE_UNREGISTRATION_IN_DAYS', 'COURSE_PRESENT_IN_PLATFORM_IN_DAYS',
       'MODULE_USED_BY_USER_IN_DAYS', 'TOTAL_NO_OF_TIMES_MODULE_OPENED',
       'ACTIVITIES_ENGAGED_WRT_MODULES', 'TOTAL_CLICKS', 'QUERIES',
       'HRABSENCE', 'CONSULTATIONS', 'ATTEDANCE', 'TENANTS',
       'RECOMMEND_COURSE_PRIORITY', 'ARE_YOU_HAPPY_WITH_COURSE',
       'PROJECTS_IN_THE_COURSE', 'PROJECTS_COMPLETED', 'MARKS',
       'PENDING_PROJECTS', 'CATEGORY', 'ISCOURSERETIRED', 'COURSE_RATING'],
      dtype='object')

In [9]:
def vectorize_text_to_cosine_mat(data):
    count_vect = CountVectorizer()
    cv_mat = count_vect.fit_transform(data)
    # Get the cosine
    cosine_sim_mat = cosine_similarity(cv_mat)
    return cosine_sim_mat

In [10]:
def get_recommendation(title,cosine_sim_mat,df,num_of_rec=10):
    # indices of the course
    course_indices = pd.Series(df.index,index=df['CATEGORY']).drop_duplicates()
    # Index of course
    idx = course_indices[title]

    # Look into the cosine matr for that index
    sim_scores =list(enumerate(cosine_sim_mat[idx]))
    sim_scores = sorted(sim_scores,reverse=True)
    selected_course_indices = [i[0] for i in sim_scores[1:]]
    selected_course_scores = [i[0] for i in sim_scores[1:]]

    # Get the dataframe & title
    result_df = df.iloc[selected_course_indices]
    result_df['similarity_score'] = selected_course_scores
    final_recommended_courses = result_df[['COURSE','USER_PROFILE','ID_USER']]
    return final_recommended_courses.head(num_of_rec)

In [11]:
def search_term_if_not_found(term,df):
    result_df = df[df['CATEGORY'].str.contains(term)]
    return result_df

In [12]:
cosine_sim_mat = vectorize_text_to_cosine_mat(df['CATEGORY'])

In [13]:
cosine_sim_mat

array([[1.        , 0.20412415, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.20412415, 1.        , 0.20412415, ..., 0.14433757, 0.25      ,
        0.13363062],
       [0.33333333, 0.20412415, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.14433757, 0.        , ..., 1.        , 0.57735027,
        0.3086067 ],
       [0.        , 0.25      , 0.        , ..., 0.57735027, 1.        ,
        0.40089186],
       [0.        , 0.13363062, 0.        , ..., 0.3086067 , 0.40089186,
        1.        ]])

In [14]:
search_term = df['CATEGORY']
search_term

0                            Python Programming Essentials
1        Using Python to Interact with the Operating Sy...
2                                  "Python Project: pillow
3                         Create Your First Python Program
4                          Python Geospatial Data Analysis
                               ...
26229           An Introduction to Practical Deep Learning
26230                        Introduction to Deep Learning
26231           An Introduction to Practical Deep Learning
26232    Introduction to Deep Learning & Neural Network...
26233    Build a Deep Learning Based Image Classifier w...
Name: CATEGORY, Length: 26234, dtype: object

In [15]:
results = get_recommendation(search_term,cosine_sim_mat,df,10)

MemoryError: Unable to allocate 3.83 TiB for an array with shape (20040362, 26234) and data type float64

In [ ]:
results

In [ ]:
d = pd.DataFrame()

In [ ]:
d = results

In [ ]:
d